version: '3'
services:
  wall-o-api:
    container_name: wall-o-api
    image: 401247062756.dkr.ecr.us-east-1.amazonaws.com/wall-o-api:latest
    ports:
      - "8080:8080"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"